### ISSUE TITLE
not able to download VirtualBox VM image

### ISSUE THREAD

**Issue by lvodenicarska** [certtools/intelmq-tutorial#12]

**Comment by ghost** [comment]
@aaronkaplan Can you please have a look? intelmq.org seems to be unreachable

**Comment by aaronkaplan** [comment]
> On 01.07.2020, at 14:55, Wagner <notifications@github.com> wrote:
> 
> 
> @aaronkaplan Can you please have a look? intelmq.org seems to be unreachable
> 

yup, was down since today ~ 11:00 AM CEST and back up now.
Xen upgrade.

Try again please.

**Comment by ghost** [comment]
> yup, was down since today ~ 11:00 AM CEST and back up now. Xen upgrade. Try again please.

Thanks! Works again
