### ISSUE TITLE
Bambenek Feed is now private and needs to be replaced

### ISSUE THREAD

**Issue by ghost** [certtools/intelmq-tutorial#9]
https://github.com/certtools/intelmq-tutorial/blob/master/lesson-2.md#configure-a-feed

Needs to be rewritten, as the feed is no more public

**Comment by mlmarkovic** [comment]
following sections are affected as well:

https://github.com/certtools/intelmq-tutorial/blob/master/lesson-2.md#experts-adding-information-to-the-stream
https://github.com/certtools/intelmq-tutorial/blob/master/lesson-2.md#experts-add-ip-2-asn-enrichment
